version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: stonks_postgres
    environment:
      POSTGRES_DB: stonks
      POSTGRES_USER: stonks
      POSTGRES_PASSWORD: stonks123
    ports:
      - "8832:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 